spring:
  profiles:
    active: dev # 开发配置,http端口为8080,数据库端口为3306,Redis端口为6379,图片上传路径为D:\RecreationPractice\upload\yoyo\
#    active: pro # 上线配置,http端口为8080,数据库端口为3307,Redis端口为6379,图片上传路径为D:\upload\yoyo\